### ISSUE TITLE
Testing inference script with facades

### ISSUE THREAD

**Issue by dcarrion87** [Shazinho10/Pix2Pix-Pytorch-Implementation#1]
Just browsing around testing pix2pix projects...

I was testing this with the [facades dataset](https://efrosgans.eecs.berkeley.edu/pix2pix/datasets/) and during training the progress saves in the outputs folder look good.

However when I test using the inference.py script at 120 epoch generator checkpoint it looks like this:

Input:

![Screenshot 2023-09-11 at 12 37 19 am](https://github.com/Shazinho10/Pix2Pix-Pytorch-Implementation/assets/2899172/051e414a-9b58-4f29-b9f0-042e8c39fa81)

Generated:

![Screenshot 2023-09-11 at 12 35 15 am](https://github.com/Shazinho10/Pix2Pix-Pytorch-Implementation/assets/2899172/edc98934-5ac4-4af7-bbda-75f783eff35f)

Not sure if you get the same?

Should inference script be using eval() and torch.no_grad?

**Comment by Shazinho10** [comment]
Can you check if the weights used in the inference were the latest or not?

**Comment by dcarrion87** [comment]
Fixing the transforms and using eval and no_grad fixed this.
